runtime: nodejs22
build:
  command:
    - bash
    - -lc
    - |
        set -euo pipefail
        METAMCP_REF="${METAMCP_REF:-}" METAMCP_REPO_URL="${METAMCP_REPO_URL:-https://github.com/metatool-ai/metamcp.git}" ./scripts/prepare-metamcp.sh
        NODE_ENV= node build/metamcp/scripts/databricks-build.mjs
command:
  - node
  - scripts/databricks-start.mjs
env:
  - name: NODE_ENV
    value: production
  - name: NPM_CONFIG_PRODUCTION
    value: "false"
  - name: NPM_CONFIG_WORKSPACES
    value: "false"
  - name: PATH
    value: /app/python/source_code/scripts/bin:/usr/local/bin:/usr/bin:/bin
  - name: FRONTEND_PORT
    value: "12008"
  - name: BACKEND_PORT
    value: "12009"
  - name: APP_URL
    value: http://127.0.0.1:12008
  - name: NEXT_PUBLIC_APP_URL
    value: http://127.0.0.1:12008
  - name: DATABASE_URL
    value: postgresql://placeholder:placeholder@127.0.0.1:5432/placeholder
  - name: BETTER_AUTH_SECRET
    value: change-me-before-production
  - name: LAKEBASE_INSTANCE_NAME
    value: dev-metamcp-lakebase-app
  - name: LAKEBASE_DATABASE_NAME
    value: dev_metamcp_app
expose:
  type: public
  port: 12008
  url_path: /
