runtime: nodejs22
build:
  command:
    - bash
    - -lc
    - |
        set -euo pipefail
        : "${METAMCP_REPO_URL:?Set METAMCP_REPO_URL (see .env.template)}"
        : "${METAMCP_REF:?Set METAMCP_REF (see .env.template)}"
        ./scripts/prepare-metamcp.sh
        NODE_ENV= node build/metamcp/scripts/databricks-build.mjs
command:
  - node
  - scripts/databricks-start.mjs
env:
  - name: NODE_ENV
    value: production
  - name: NPM_CONFIG_PRODUCTION
    value: "false"
  - name: NPM_CONFIG_WORKSPACES
    value: "false"
  - name: PATH
    value: /app/python/source_code/scripts/bin:/usr/local/bin:/usr/bin:/bin
  # Databricks injects DATABRICKS_APP_PORT - we use it via databricks-start.mjs
  # Backend runs on a separate internal port calculated from DATABRICKS_APP_PORT + 1
  # DATABASE_URL is built dynamically by databricks-start.mjs from:
  # - PGHOST, PGPORT, PGDATABASE, PGUSER, PGSSLMODE (from Lakebase resource)
  # - PGPASSWORD (fetched via OAuth using DATABRICKS_CLIENT_ID/SECRET)
  - name: BETTER_AUTH_SECRET
    value: ${BETTER_AUTH_SECRET}
  # Instance name must match databricks.yml database_instances.*.name
  - name: LAKEBASE_INSTANCE_NAME
    value: metamcp-lakebase
  - name: LAKEBASE_DATABASE_NAME
    value: postgres
  - name: METAMCP_REPO_URL
    value: ${METAMCP_REPO_URL}
  - name: METAMCP_REF
    value: ${METAMCP_REF}
expose:
  type: public
  port: 12008
  url_path: /
